---
- name: Configure web servers
  hosts: webservers
  gather_facts: true
  become: true
  any_errors_fatal: false
  tags: [webservers]
  roles:
    - role: common
      tags: [common]
    - role: webserver
      tags: [webserver]

- name: Configure database servers
  hosts: databases
  gather_facts: true
  become: true
  any_errors_fatal: false
  tags: [databases]
  roles:
    - role: common
      tags: [common]
    - role: database
      tags: [database]
