apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.appName }}-secrets"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.appName }}"
    component: secrets
type: Opaque
data:
  database-url: "{{ .Values.database.url | b64enc }}"
  jwt-secret: "{{ .Values.backend.jwtSecret | b64enc }}"
  mysql-root-password: "{{ .Values.database.rootPassword | b64enc }}"
  mysql-password: "{{ .Values.database.password | b64enc }}"
  api-key: "{{ .Values.backend.apiKey | b64enc }}"
  redis-url: "{{ .Values.redis.url | b64enc }}"
  encryption-key: "{{ .Values.backend.encryptionKey | b64enc }}"
  api-key-hash: "{{ .Values.backend.apiKeyHash | b64enc }}"
