apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "{{ .Values.appName }}-backend-pdb"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.appName }}-backend"
    environment: "{{ .Values.environment }}"
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: "{{ .Values.appName }}-backend"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "{{ .Values.appName }}-frontend-pdb"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.appName }}-frontend"
    environment: "{{ .Values.environment }}"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: "{{ .Values.appName }}-frontend"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "{{ .Values.appName }}-database-pdb"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.appName }}-database"
    environment: "{{ .Values.environment }}"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: "{{ .Values.appName }}-database"
