apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-redis"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.appName }}-redis"
    tier: cache
    component: redis
    environment: "{{ .Values.environment }}"
spec:
  type: ClusterIP
  ports:
    - port: { { .Values.redis.servicePort } }
      targetPort: { { .Values.redis.containerPort } }
      protocol: TCP
      name: redis
  selector:
    app: "{{ .Values.appName }}-redis"
