apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.appName }}-redis-pvc"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.appName }}-redis"
    tier: cache
    environment: "{{ .Values.environment }}"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "{{ .Values.redis.storageClass }}"
  resources:
    requests:
      storage: "{{ .Values.redis.storage }}"
